server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.229.223:3306/tensquare_gathering?characterEncoding=UTF8
    username: work
    password: work
  jpa: 
    database: MySQL
    show-sql: true

